### ISSUE TITLE
Adding the Brain Dynamics Toolbox

### ISSUE THREAD

**Issue by stewart-heitmann** [asoplata/open-computational-neuroscience-resources#9]
Dear asoplata,
could you please add the Brain Dynamics Toolbox to your list of simulators?

- [Brain Dynamics Toolbox - Open software for simulating dynamical systems in neuroscience using Matlab](https://bdtoolbox.org) 

Kind Regards,
Stewart Heitmann

**Comment by asoplata** [comment]
Thanks so much! Done!
